# Inspired from: https://github.com/seeM/blog
name: Quarto Publish
on:
  # Triggers the workflow on push or pull request events but only for the "main" branch
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build-deploy:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v4
      # Quarto actions find out more here: https://github.com/quarto-dev/quarto-actions?tab=readme-ov-file
      - uses: quarto-dev/quarto-actions/setup@v2
        with:
          version: pre-release
        run: |
            R -e 'install.packages(c("rmarkdown", "knitr"))'
      - name: Render and Publish
        uses: quarto-dev/quarto-actions/publish@v2
        with:
          target: gh-pages
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
